### ISSUE TITLE
Todo feature list

### ISSUE THREAD

**Issue by Syriiin** [Syriiin/unicircle-visualiser#1]
- [ ] Refactor into a neat codebase
- [ ] Zoom + pan charts
- [ ] Hover tooltips for chart data points
- [ ] Select data point to lock map preview time to when not hovering over charts (also highlight selected object on preview)
- [ ] Scroll on map preview to move time
